---
language: bash

dist: trusty

env:
  - VERSION=9.0-2.1
  - VERSION=9.1-2.1
  - VERSION=9.2-2.1
  - VERSION=9.3-2.1
  - VERSION=9.4-2.1

before_script:
  - env | sort
  - cd "$VERSION"
  - image="appropriate/postgis:$VERSION"

script:
  - docker build --pull -t "$image" .
